version: '3'

services:
  my-app:
    image: oshrimeg/flask-contacts-app:latest
    ports:
      - "5000:5000"  
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
    depends_on:
      - mysql

  mysql:
    image: mysql:latest  
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mydatabase  
      MYSQL_USER: user  
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
